# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

on:
  workflow_call:
    inputs:
      py:
        type: string
        default: '3.11'

jobs:
  lint:
    name: Lint
    runs-on:
      labels: 4-core-ubuntu
    container:
      image: ghcr.io/facebookresearch/fairseq2-ci-manylinux_x86_64:2-cpu
    defaults:
      run:
        shell: bash
    steps:
      - name: Check-out the repository
        uses: actions/checkout@v3
<<<<<<< HEAD
<<<<<<< HEAD
=======
      - name: Install libsndfile
        run: |
          yum --assumeyes install libsndfile-devel
      - name: Install libpng-dev
        run: |
          yum --assumeyes install libpng-devel
      - name: Install libjpeg-dev
        run: |
<<<<<<< HEAD
<<<<<<< HEAD
          yum --assumeyes install libjpeg-devel
>>>>>>> 9be595fe (fix typo)
=======
          yum --assumeyes install libjpeg-devel-2.1.2
>>>>>>> 9caad8cc (download libjpeg 1.5 and use const data_ptr)
=======
          yum --assumeyes install https://rpmfind.net/linux/centos/8-stream/AppStream/x86_64/os/Packages/libjpeg-turbo-1.5.3-12.el8.x86_64.rpm
          yum --assumeyes install https://rpmfind.net/linux/centos/8-stream/AppStream/x86_64/os/Packages/libjpeg-turbo-devel-1.5.3-12.el8.x86_64.rpm 
>>>>>>> a06b73b1 (libjpeg 1.5)
=======
>>>>>>> 7a2c1170 (fix lint)
      - name: Create the Python virtual environment
        run: |
          python${{ inputs.py }} -m venv ~/venv

          echo ~/venv/bin >> "$GITHUB_PATH"
      - name: Install requirements
        id: setup
        run: |
          pip install --requirement requirements-devel.txt
      - name: Run shellcheck
        if: success() || (failure() && steps.setup.outcome == 'success')
        run: |
          echo "::add-matcher::./ci/problem-matchers/gcc.json"

          function remove_matcher
          {
            echo "::remove-matcher owner=gcc::"
          }

          trap remove_matcher EXIT

          tools/run-shellcheck.sh .
